spring:
  application:
    name: invoice-verification-system
  profiles:
    default: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB

aws:
  region: ${AWS_REGION:ap-south-1}

server:
  shutdown: graceful

spring.lifecycle:
  timeout-per-shutdown-phase: 20s
