CREATE TABLE IF NOT EXISTS brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT NOT NULL REFERENCES brands(id),
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT NOT NULL REFERENCES brands(id),
    invoice_number VARCHAR(100),
    reference_number VARCHAR(100),
    sku VARCHAR(100),
    purchase_date DATE,
    custom_data TEXT,
    name VARCHAR(150),
    email VARCHAR(255),
    phone VARCHAR(50),
    country VARCHAR(100),
    purchased_from VARCHAR(255),
    marketing_consent BOOLEAN,
    object_key VARCHAR(500) NOT NULL,
    verification_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS invoice_verification_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id),
    old_status VARCHAR(20) NOT NULL,
    new_status VARCHAR(20) NOT NULL,
    changed_by VARCHAR(255) NOT NULL,
    review_note VARCHAR(1000),
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_invoices_brand_created ON invoices (brand_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoice_history_invoice ON invoice_verification_history (invoice_id, changed_at DESC);
INSERT INTO brands (slug, display_name, active) VALUES ('aigner', 'AIGNER', TRUE) ON CONFLICT (slug) DO NOTHING;
